apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: lion-app
  labels:
    app: member-service
spec:
  type: ClusterIP
  selector:
    app: member-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
