dependencies {
    implementation project(':modules:common')

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'software.amazon.awssdk:s3:2.25.20'

    testImplementation 'com.h2database:h2'
    testImplementation 'org.springframework.security:spring-security-test'
}
