-- 로컬 데모 데이터 (클러스터 B — ai_db)
--
-- lion_memories 는 엔티티 모양대로 만든다. embedding 은 vector(1024) 이며
-- pgvector 확장이 00-init.sql 에서 이미 설치됐다.

CREATE TABLE IF NOT EXISTS ai_db.lions (
    lion_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL UNIQUE,
    level        INT NOT NULL DEFAULT 1,
    exp          BIGINT NOT NULL DEFAULT 0,
    growth_stage VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_db.lion_memories (
    lion_memory_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lion_id         BIGINT NOT NULL,
    book_id         BIGINT NOT NULL,
    book_title      VARCHAR(255),
    cover_url       VARCHAR(500),
    memo            TEXT,
    quote_text      TEXT,
    finished_at     TIMESTAMP,
    embedding       vector(1024),
    embedding_model VARCHAR(100),
    embedding_dim   INT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_db.inquiries (
    inquiry_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL,
    nickname     VARCHAR(50),
    book_id      BIGINT,
    book_title   VARCHAR(255),
    title        VARCHAR(255) NOT NULL,
    content      TEXT NOT NULL,
    admin_answer TEXT,
    answered     BOOLEAN NOT NULL DEFAULT FALSE,
    answered_at  TIMESTAMP,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_db.faqs (
    faq_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   VARCHAR(100) NOT NULL,
    question   VARCHAR(500) NOT NULL,
    answer     TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- member_id 는 member_db 의 값이지만 FK 가 없다. 클러스터가 아예 달라서
-- FK 를 걸 방법도 없다 — 그게 격리의 증거다.
INSERT INTO ai_db.lions (member_id, growth_stage) VALUES (1, 'CUB')
ON CONFLICT (member_id) DO NOTHING;

INSERT INTO ai_db.faqs (category, question, answer, sort_order) VALUES
    ('배송', '배송은 얼마나 걸리나요?', '결제 완료 후 영업일 기준 2~3일 소요됩니다.', 1),
    ('주문', '주문 취소는 어떻게 하나요?', '배송 준비중 상태까지는 마이페이지에서 직접 취소할 수 있습니다.', 2);

-- 소유권 이전 — GRANT 만으로는 ddl-auto 가 인덱스/제약을 못 붙인다.
-- (cluster-a/90-demo-data.sql 의 같은 블록과 이유가 같다)
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'ai_db' LOOP
        EXECUTE format('ALTER TABLE ai_db.%I OWNER TO ai_svc', r.tablename);
    END LOOP;

    FOR r IN SELECT sequence_name FROM information_schema.sequences WHERE sequence_schema = 'ai_db' LOOP
        EXECUTE format('ALTER SEQUENCE ai_db.%I OWNER TO ai_svc', r.sequence_name);
    END LOOP;
END $$;
