/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/wishlist/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addWishlist"];
        delete: operations["removeWishlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReviews"];
        put?: never;
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wishlist/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyWishlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent-books/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyRecentBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/synopsis/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSynopsisDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/new-releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNewReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/bestsellers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBestsellers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: Record<string, never>;
            error?: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            code?: string;
            message?: string;
        };
        ReviewRequest: {
            /** Format: int32 */
            rating?: number;
            content: string;
        };
        ApiResponseReviewResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReviewResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        ReviewResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            bookId?: number;
            /** Format: int64 */
            memberId?: number;
            nickname?: string;
            /** Format: int32 */
            rating?: number;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListBookSummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BookSummaryResponse"][];
            error?: components["schemas"]["ErrorDetail"];
        };
        BookSummaryResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            author?: string;
            /** Format: int32 */
            price?: number;
            coverImageUrl?: string;
            category?: string;
            /** @enum {string} */
            saleStatus?: "ON_SALE" | "STOPPED" | "OUT_OF_STOCK";
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageBookSummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageBookSummaryResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        PageBookSummaryResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["BookSummaryResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        PageableObject: {
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
        };
        SortObject: {
            sorted?: boolean;
            unsorted?: boolean;
            empty?: boolean;
        };
        ApiResponseBookDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BookDetailResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        BookDetailResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            author?: string;
            publisher?: string;
            isbn?: string;
            category?: string;
            /** Format: int32 */
            price?: number;
            /** Format: int32 */
            stockQuantity?: number;
            coverImageUrl?: string;
            description?: string;
            /** @enum {string} */
            saleStatus?: "ON_SALE" | "STOPPED" | "OUT_OF_STOCK";
            /** Format: date */
            publishedDate?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseBookSynopsisDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BookSynopsisDetailResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        BookSynopsisDetailResponse: {
            /** Format: int64 */
            bookId?: number;
            title?: string;
            detailedSynopsis?: string;
        };
        ApiResponsePageReviewResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageReviewResponse"];
            error?: components["schemas"]["ErrorDetail"];
        };
        PageReviewResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ReviewResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    addWishlist: {
        parameters: {
            query?: never;
            header: {
                "X-Member-Id": number;
            };
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    removeWishlist: {
        parameters: {
            query?: never;
            header: {
                "X-Member-Id": number;
            };
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getReviews: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageReviewResponse"];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header: {
                "X-Member-Id": number;
            };
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReviewResponse"];
                };
            };
        };
    };
    getMyWishlist: {
        parameters: {
            query?: never;
            header: {
                "X-Member-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBookSummaryResponse"];
                };
            };
        };
    };
    getMyRecentBooks: {
        parameters: {
            query?: {
                limit?: number;
            };
            header: {
                "X-Member-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBookSummaryResponse"];
                };
            };
        };
    };
    getBooks: {
        parameters: {
            query: {
                category?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageBookSummaryResponse"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: {
                "X-Member-Id"?: number;
            };
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookDetailResponse"];
                };
            };
        };
    };
    getSynopsisDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookSynopsisDetailResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageBookSummaryResponse"];
                };
            };
        };
    };
    getNewReleases: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBookSummaryResponse"];
                };
            };
        };
    };
    getBestsellers: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBookSummaryResponse"];
                };
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header: {
                "X-Member-Id": number;
            };
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
