plugins {
    id 'org.springframework.boot'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}

dependencies {
    implementation project(':modules:common')
    implementation project(':modules:member')
    implementation project(':modules:book')
    implementation project(':modules:order')
    implementation project(':modules:usedbook')
    implementation project(':modules:delivery')

    // Flyway DB Migration
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'

    // MySQL Connector
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Swagger (Springdoc OpenAPI)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

    // AWS S3 / Image utilities (선택)
    implementation 'software.amazon.awssdk:s3:2.25.20'
    implementation 'net.coobird:thumbnailator:0.4.20'
    implementation 'com.twelvemonkeys.imageio:imageio-webp:3.12.0'

    testImplementation 'org.springframework.security:spring-security-test'
}
