-- =============================================================================
-- 로컬 데모 데이터 (클러스터 1개 — 4개 스키마)
--
-- 여기 있는 CREATE TABLE 은 db/postgres/01~04 의 "목표 스키마"가 아니라
-- **현재 JPA 엔티티 모양**이다. 전환 전 저장소에서도 같은 구조였다 —
-- 엔티티와 schema.sql 이 아직 정렬되지 않았고(예: members 는 엔티티가
-- cognito_sub 를 쓰는데 목표 스키마는 username/password 를 쓴다),
-- docker-compose 는 ddl-auto: update 로 뜨기 때문이다.
--
-- 그래서 01~04 파일은 마운트하지 않는다. 그것들은 Flyway 로 넘어갈 때의
-- 목표 스키마 참조본이고, 실제 로컬 기동은 이 파일 + ddl-auto 가 담당한다.
-- (전환 전에도 schema.sql 을 넣지 않고 1_demo_data.sql 만 넣었던 것과 같다)
--
-- 각 테이블이 어느 스키마에 들어가는지가 MSA 전환의 결과물이다.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- member_db
-- ---------------------------------------------------------------------------
-- member_id 는 auto-increment PK가 아니라 Cognito sub 값을 그대로 저장한다(PK 구조 변경,
-- Member.java 참고). 별도 cognito_sub 컬럼은 없다.
CREATE TABLE IF NOT EXISTS member_db.members (
    member_id    VARCHAR(255) PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,
    name         VARCHAR(255) NOT NULL,
    nickname     VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(20),
    gender       VARCHAR(10),
    birth_date   DATE,
    role         VARCHAR(20) NOT NULL DEFAULT 'USER',
    grade        VARCHAR(20) NOT NULL DEFAULT 'BRONZE',
    point        INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO member_db.members (member_id, email, name, nickname, role, grade)
VALUES ('00000000-0000-0000-0000-000000000001', 'test@lion.com', '테스트유저', '테스트유저', 'USER', 'BRONZE')
ON CONFLICT (member_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- catalog_db
-- books 에 stock_quantity 가 없는 것이 Phase 0-1 의 결과다.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS catalog_db.categories (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    parent_id     BIGINT,
    sort_order    INT NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO catalog_db.categories (category_name, sort_order)
VALUES ('IT/컴퓨터', 1), ('소설', 2), ('자기계발', 3), ('경제경영', 4), ('에세이', 5), ('인문', 6)
ON CONFLICT (category_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS catalog_db.books (
    book_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(200) NOT NULL,
    author            VARCHAR(100) NOT NULL,
    publisher         VARCHAR(100) NOT NULL,
    isbn              CHAR(13) NOT NULL UNIQUE,
    category          VARCHAR(100) NOT NULL,
    price             BIGINT NOT NULL,
    cover_image_url   VARCHAR(500),
    epub_s3_key       VARCHAR(500),
    description       TEXT,
    detailed_synopsis TEXT,
    sale_status       VARCHAR(20) NOT NULL DEFAULT 'ON_SALE',
    published_date    DATE,
    sales_count       INT NOT NULL DEFAULT 0,
    rating_avg        DECIMAL(3, 2) NOT NULL DEFAULT 0.00,
    review_count      INT NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO catalog_db.books (
    title, author, publisher, isbn, category, price,
    cover_image_url, description, detailed_synopsis, sale_status, published_date, sales_count
) VALUES (
    '클라우드 엔지니어링 교재',
    '북이팅라이언',
    '라이언출판사',
    '9791100000001',
    'IT/컴퓨터',
    25000,
    '/covers/it-01.png',
    '클라우드 엔지니어링의 기초부터 실전까지 다루는 교재입니다.',
    '1장 클라우드 개론, 2장 컨테이너와 오케스트레이션, 3장 CI/CD 파이프라인 구축, 4장 관측성과 운영을 다루며, 마지막 장에서는 실제 장애 대응 사례를 상세히 재구성하여 소개한다.',
    'ON_SALE',
    '2026-01-15',
    42
) ON CONFLICT (isbn) DO NOTHING;

-- RAG 인제스트 테스트용 도서 2권.
--
-- book_id 를 명시하는 이유는 S3 의 EPUB 키와 짝을 맞춰야 하기 때문이다.
-- 인제스트 메시지의 epubS3Key 가 books/{bookId}/... 규칙이라 ID 가 흔들리면
-- 벡터 메타데이터의 bookId 와 실제 도서가 어긋난다. 그러면 "구매한 책만 검색"
-- 권한 검사가 엉뚱한 책을 통과시킨다.
--
-- 100번대를 쓴 건 자동 채번(1번부터)과 겹치지 않게 하기 위해서다.
--   books/101/frankenstein.epub
--   books/102/alice-in-wonderland.epub
-- 버킷은 AI_EPUB_BUCKET 이며 메시지에는 키만 담긴다.
INSERT INTO catalog_db.books (
    book_id, title, author, publisher, isbn, category, price,
    cover_image_url, description, detailed_synopsis, sale_status, published_date, sales_count
) VALUES (
    101,
    'Frankenstein',
    'Mary Shelley',
    'Project Gutenberg',
    '9791100000101',
    '소설',
    12000,
    '/covers/novel-01.png',
    '생명을 창조한 과학자와 그가 만든 피조물의 이야기.',
    '빅터 프랑켄슈타인이 생명의 비밀을 밝혀 피조물을 만들지만 그 모습에 스스로 도망치고, 버려진 피조물이 창조주를 뒤쫓으며 벌어지는 추격과 대화를 담는다.',
    'ON_SALE',
    '1818-01-01',
    0
), (
    102,
    'Alice''s Adventures in Wonderland',
    'Lewis Carroll',
    'Project Gutenberg',
    '9791100000102',
    '소설',
    9000,
    '/covers/novel-02.png',
    '토끼굴에 빠진 소녀가 겪는 기묘한 모험.',
    '앨리스가 조끼를 입은 흰토끼를 쫓아 굴에 빠진 뒤, 몸이 커졌다 작아졌다 하며 미친 모자장수의 다과회와 하트 여왕의 재판을 거치는 이야기.',
    'ON_SALE',
    '1865-11-26',
    0
) ON CONFLICT (isbn) DO NOTHING;

-- 카탈로그 화면 데모용 추가 도서 21권 (가상 도서 — 실존 도서 아님, 저작권/사실관계
-- 문제를 피하려고 제목·저자·출판사·줄거리 전부 지어냈다). book_id는 자동 채번에
-- 맡긴다 — 101/102보다 한참 앞선 번호대만 쓰므로 아래 시퀀스 재설정과 충돌하지 않는다.
-- 전부 "일반" 도서로 epub_s3_key는 없다(NULL 기본값 유지).
INSERT INTO catalog_db.books (
    title, author, publisher, isbn, category, price,
    cover_image_url, description, detailed_synopsis, sale_status, published_date, sales_count
) VALUES
-- IT/컴퓨터
(
    '실전 마이크로서비스 설계', '한동혁', '코드포레스트', '9791100000002', 'IT/컴퓨터', 27000,
    '/covers/it-02.png',
    '서비스 분리 기준부터 장애 대응까지, 실무에서 바로 쓰는 마이크로서비스 설계 가이드.',
    '도메인 경계를 나누는 기준, 서비스 간 통신 패턴, 장애 전파를 막는 회복 탄력성 설계까지 다룬다.',
    'ON_SALE', '2024-03-10', 58
),
(
    '처음 배우는 파이썬 데이터 분석', '윤소라', '비트북스', '9791100000003', 'IT/컴퓨터', 24000,
    '/covers/it-03.png',
    '파이썬 기초부터 데이터 시각화까지 손에 잡히는 데이터 분석 입문서.',
    '판다스로 데이터를 다루고 그래프로 시각화하는 과정을 실습 예제로 따라가며 익힌다.',
    'ON_SALE', '2023-09-01', 121
),
(
    '쉽게 이해하는 네트워크의 원리', '강태민', '테크노트', '9791100000004', 'IT/컴퓨터', 22000,
    '/covers/it-04.png',
    'TCP/IP부터 HTTP까지, 그림으로 이해하는 네트워크 기초.',
    '패킷이 오가는 과정을 그림으로 풀어 설명하며, 실무에서 자주 마주치는 네트워크 트러블슈팅 사례도 함께 다룬다.',
    'ON_SALE', '2024-11-20', 34
),
-- 소설
(
    '여름이 끝나는 자리', '김하은', '온다책방', '9791100000103', '소설', 15800,
    '/covers/novel-03.png',
    '한 계절의 끝에서 만난 두 사람의 짧고 깊은 인연을 그린 소설.',
    '바닷가 마을에서 우연히 재회한 두 사람이 서로의 상처를 알아가며 여름을 함께 통과하는 이야기.',
    'ON_SALE', '2024-07-05', 76
),
(
    '밤의 지도', '이서준', '소요서가', '9791100000104', '소설', 16500,
    '/covers/novel-04.png',
    '잠 못 이루는 도시의 밤, 각자의 사정을 안고 걷는 사람들의 이야기.',
    '택시기사, 편의점 야간 알바생, 불면증에 시달리는 회사원의 시선이 교차하며 하나의 밤을 완성한다.',
    'ON_SALE', '2025-01-22', 19
),
-- 자기계발
(
    '아주 작은 습관의 재발견', '박지훈', '마인드셋', '9791100000201', '자기계발', 16000,
    '/covers/selfhelp-01.png',
    '거창한 결심 대신 하루 5분의 작은 습관으로 삶을 바꾸는 법.',
    '습관이 자리 잡는 데 필요한 최소 단위의 행동을 제안하고, 실패해도 다시 시작하는 회복 루틴을 소개한다.',
    'ON_SALE', '2023-05-15', 145
),
(
    '오늘부터 미루지 않기로 했다', '최유리', '라이프하우스', '9791100000202', '자기계발', 15000,
    '/covers/selfhelp-02.png',
    '미루는 습관의 심리적 원인과 실전 극복법을 담은 자기계발서.',
    '완벽주의와 불안이 어떻게 지연 행동으로 이어지는지 짚고, 5분만 시작해보는 작은 트리거들을 제시한다.',
    'ON_SALE', '2024-02-14', 88
),
(
    '생각을 정리하는 기술', '정다솔', '클리어마인드', '9791100000203', '자기계발', 15500,
    '/covers/selfhelp-03.png',
    '머릿속이 복잡할 때 생각을 글로 꺼내 정리하는 방법.',
    '메모, 마인드맵, 우선순위표 등 도구별 활용법을 소개하며 결정 피로를 줄이는 루틴을 제안한다.',
    'ON_SALE', '2024-08-30', 41
),
(
    '나를 지키는 대화법', '한소이', '마음정원', '9791100000204', '자기계발', 14800,
    '/covers/selfhelp-04.png',
    '관계에서 지치지 않고 내 의견을 전하는 대화 기술.',
    '거절하는 법, 감정을 다치지 않게 표현하는 법 등 실생활 대화 예시로 경계 세우기를 연습한다.',
    'ON_SALE', '2025-03-03', 12
),
-- 경제경영
(
    '돈의 심리학 노트', '장민석', '이코노미프레스', '9791100000301', '경제경영', 18000,
    '/covers/biz-01.png',
    '돈에 대한 우리의 태도가 어디서 비롯되는지 살펴보는 실용 경제 교양서.',
    '저축과 소비, 투자 앞에서 사람들이 반복하는 비합리적 선택들을 사례 중심으로 짚어보고, 돈과 건강한 거리를 두는 법을 제안한다.',
    'ON_SALE', '2023-11-11', 103
),
(
    '스타트업 재무제표 읽는 법', '윤재국', '비즈니스맵', '9791100000302', '경제경영', 19500,
    '/covers/biz-02.png',
    '숫자에 약한 창업자를 위한 손익계산서·재무상태표 입문서.',
    '매출과 이익의 차이부터 현금흐름표를 읽는 법까지, 실제 스타트업 사례로 재무제표의 뼈대를 짚는다.',
    'ON_SALE', '2024-06-18', 27
),
(
    '투자자의 첫걸음', '서인우', '웰스노트', '9791100000303', '경제경영', 17000,
    '/covers/biz-03.png',
    '주식 투자를 처음 시작하는 사람을 위한 개념 정리.',
    '분산 투자, 복리, 시장 사이클 같은 기본 개념을 쉬운 비유로 설명하며 조급함을 다스리는 법을 함께 이야기한다.',
    'ON_SALE', '2024-04-09', 64
),
(
    '브랜드는 어떻게 살아남는가', '오하람', '마케팅랩', '9791100000304', '경제경영', 18500,
    '/covers/biz-04.png',
    '치열한 시장에서 오래가는 브랜드의 공통점을 분석한 마케팅 에세이.',
    '국내외 브랜드 사례를 통해 일관된 메시지와 고객 신뢰가 어떻게 브랜드 수명을 늘리는지 살펴본다.',
    'ON_SALE', '2025-02-01', 8
),
-- 에세이
(
    '혼자여도 괜찮은 계절', '문소연', '바람같이', '9791100000401', '에세이', 14500,
    '/covers/essay-01.png',
    '혼자 보내는 시간의 의미를 담담히 풀어낸 에세이.',
    '여행, 식사, 산책 같은 일상의 장면들을 통해 혼자 있는 시간이 주는 위로를 이야기한다.',
    'ON_SALE', '2023-10-05', 97
),
(
    '느리게 걷는 하루', '배지원', '나무그늘', '9791100000402', '에세이', 14000,
    '/covers/essay-02.png',
    '바쁜 일상 속 잠시 멈춰 걷는 시간의 소중함을 담은 산문집.',
    '출퇴근길, 동네 산책, 계절의 변화를 관찰하며 느리게 사는 감각을 되찾는 기록이다.',
    'ON_SALE', '2024-09-12', 53
),
(
    '커피 한 잔의 위로', '김라온', '온기출판', '9791100000403', '에세이', 13500,
    '/covers/essay-03.png',
    '카페에서 마주친 사람들과 순간들을 담은 짧은 에세이 모음.',
    '낯선 이의 다정함, 익숙한 단골 가게의 온기 같은 소소한 장면들을 통해 하루를 견디는 힘을 이야기한다.',
    'ON_SALE', '2024-12-25', 31
),
(
    '서툴러도 괜찮아', '이하늘', '소소책방', '9791100000404', '에세이', 14200,
    '/covers/essay-04.png',
    '완벽하지 않아도 나아가는 삶의 태도를 다룬 에세이.',
    '실수와 실패를 마주하는 저자의 경험을 통해 서툰 나 자신과 화해하는 과정을 그린다.',
    'ON_SALE', '2025-01-08', 15
),
-- 인문
(
    '질문하는 인간', '조현우', '사유의숲', '9791100000501', '인문', 19000,
    '/covers/humanities-01.png',
    '인간을 인간답게 만드는 것은 답이 아니라 질문이라는 주제의 인문 교양서.',
    '철학사 속 유명한 질문들을 따라가며 스스로 사고하는 힘을 기르는 법을 이야기한다.',
    'ON_SALE', '2023-08-20', 112
),
(
    '역사를 바꾼 열 가지 순간', '남궁민', '지식정원', '9791100000502', '인문', 20000,
    '/covers/humanities-02.png',
    '역사의 흐름을 바꾼 결정적 사건 열 가지를 골라 다시 읽는 교양서.',
    '우연과 선택이 뒤섞인 순간들을 통해 역사가 필연이 아니라 사람의 결정이었음을 보여준다.',
    'ON_SALE', '2024-05-27', 46
),
(
    '철학이 있는 저녁', '백유진', '사색출판', '9791100000503', '인문', 17500,
    '/covers/humanities-03.png',
    '퇴근 후 잠깐, 철학자들의 생각을 가볍게 곱씹어보는 인문 에세이.',
    '소크라테스부터 현대 철학자까지, 일상의 질문에 빗대어 철학의 핵심 개념을 풀어낸다.',
    'ON_SALE', '2024-10-14', 22
),
(
    '우리는 왜 이야기를 좋아하는가', '심다인', '인문서가', '9791100000504', '인문', 18800,
    '/covers/humanities-04.png',
    '인간이 이야기에 끌리는 이유를 심리와 문화 양쪽에서 살펴보는 책.',
    '신화, 소설, 영화 속 이야기 구조를 비교하며 이야기가 공동체를 묶는 힘을 설명한다.',
    'ON_SALE', '2025-02-19', 6
)
ON CONFLICT (isbn) DO NOTHING;

-- 🔴 위에서 book_id 를 직접 넣었으므로 시퀀스는 그대로 2에 머물러 있다.
-- 그냥 두면 이후 자동 채번이 2, 3, ... 으로 올라가다 101 에서 충돌한다.
-- 데모 데이터가 앱의 정상 동작을 나중에 깨뜨리지 않도록 여기서 밀어둔다.
ALTER TABLE catalog_db.books ALTER COLUMN book_id RESTART WITH 103;

-- book_id 101/102 는 S3 에 실제 업로드된 EPUB 을 가리킨다 (aws s3 ls 로 확인).
UPDATE catalog_db.books SET epub_s3_key = 'books/101/frankenstein.epub' WHERE book_id = 101;
UPDATE catalog_db.books SET epub_s3_key = 'books/102/alice-in-wonderland.epub' WHERE book_id = 102;

CREATE TABLE IF NOT EXISTS catalog_db.reviews (
    review_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id       BIGINT NOT NULL,
    member_id     BIGINT NOT NULL,
    order_item_id BIGINT,
    nickname      VARCHAR(50),
    rating        INT NOT NULL,
    content       TEXT NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalog_db.wishlists (
    wishlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL,
    book_id     BIGINT NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wishlists_member_book UNIQUE (member_id, book_id)
);

CREATE TABLE IF NOT EXISTS catalog_db.recent_books (
    recent_book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT NOT NULL,
    book_id        BIGINT NOT NULL,
    viewed_at      TIMESTAMP NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_recent_books_member_book UNIQUE (member_id, book_id)
);

-- 리뷰를 쓰려면 이 권한이 먼저 있어야 한다. 운영에서는 order-service 가
-- 구매 확정 시 Redis Streams 로 발행하지만, 로컬 데모용으로 1건 심어둔다.
CREATE TABLE IF NOT EXISTS catalog_db.review_permissions (
    member_id     BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    book_id       BIGINT NOT NULL,
    nickname      VARCHAR(50),
    granted_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at       TIMESTAMP,
    PRIMARY KEY (member_id, order_item_id)
);

INSERT INTO catalog_db.review_permissions (member_id, order_item_id, book_id, nickname)
VALUES (1, 1, 1, '테스트유저')
ON CONFLICT (member_id, order_item_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- order_db
-- 재고가 여기 있다. catalog 는 이 테이블을 조회할 권한이 없고,
-- /internal/inventory API 를 통해서만 값을 얻는다.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_db.inventory (
    book_id    BIGINT PRIMARY KEY,
    stock      INT NOT NULL DEFAULT 0,
    version    BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 101/102 는 RAG 인제스트 테스트용 도서다. 재고가 없으면 주문 자체가 막혀
-- 구매확정 이벤트가 발행되지 않고, 그러면 "구매한 책만 검색" 권한도 생기지 않는다.
INSERT INTO order_db.inventory (book_id, stock) VALUES (1, 100), (101, 100), (102, 100)
ON CONFLICT (book_id) DO NOTHING;

-- CREATE TABLE IF NOT EXISTS order_db.orders (
--     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     member_id  BIGINT NOT NULL,
--     book_id    BIGINT NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- orders/deliveries 는 여기서 만들지 않는다 — Order/Delivery 엔티티가 이미 있고
-- ddl-auto: update 가 order-service 기동 시 만든다(주문/결제 구현 이전에는 이 자리에
-- member_id+book_id 두 컬럼짜리 임시 테이블과 데모 행을 수동으로 만들었는데, 그게
-- Order 엔티티의 실제 컬럼(recipient_name/address/order_status 등 NOT NULL)과
-- 어긋나면서 ddl-auto 의 ALTER TABLE ADD COLUMN NOT NULL 이 매번 실패했다 —
-- 기존 행이 새 NOT NULL 컬럼 값을 가질 수 없어서다. cart_items/coupons/payments 등
-- 다른 order_db 테이블도 전부 같은 이유로 여기서 수동 생성하지 않는다).

-- CREATE TABLE IF NOT EXISTS order_db.deliveries (
--     id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     order_id        BIGINT NOT NULL UNIQUE,
--     courier_company VARCHAR(100),
--     tracking_number VARCHAR(100),
--     delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
--     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- INSERT INTO order_db.orders (member_id, book_id) VALUES (1, 1);
-- INSERT INTO order_db.deliveries (order_id, courier_company, tracking_number, delivery_status)
-- VALUES (1, 'CJ대한통운', '123456789', 'IN_TRANSIT')
-- ON CONFLICT (order_id) DO NOTHING;


-- ---------------------------------------------------------------------------
-- 소유권 이전 — GRANT 만으로는 부족하다.
--
-- 데모 테이블을 superuser 가 만들었기 때문에, ddl-auto: update 로 뜬 서비스가
-- 인덱스나 제약을 덧붙이려 하면 "must be owner of table ..." 로 실패한다.
-- (SELECT/INSERT 권한과 DDL 변경 권한은 별개다)
--
-- 운영에서는 Flyway 가 서비스 계정으로 마이그레이션하므로 이 문제가 없다.
-- 로컬에서만 필요한 보정이다.
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- ai_db  (구 클러스터 B. pgvector 를 버리면서 같은 클러스터로 합쳤다)
--   벡터는 여기 없다 — 전부 S3 Vectors 인덱스 wiki-v1 에 있다.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_db.lions (
    lion_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL UNIQUE,
    level        INT NOT NULL DEFAULT 1,
    exp          BIGINT NOT NULL DEFAULT 0,
    growth_stage VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_db.inquiries (
    inquiry_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL,
    nickname     VARCHAR(50),
    book_id      BIGINT,
    book_title   VARCHAR(255),
    title        VARCHAR(255) NOT NULL,
    content      TEXT NOT NULL,
    admin_answer TEXT,
    answered     BOOLEAN NOT NULL DEFAULT FALSE,
    answered_at  TIMESTAMP,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_db.faqs (
    faq_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   VARCHAR(100) NOT NULL,
    question   VARCHAR(500) NOT NULL,
    answer     TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- member_id 는 member_db 의 값이지만 FK 가 없다. 같은 클러스터가 됐어도 걸지 않는다 —
-- 스키마 경계를 넘는 조인은 계정 권한이 막고, FK 는 그 경계를 다시 뚫는 짓이다.
INSERT INTO ai_db.lions (member_id, growth_stage) VALUES (1, 'CUB')
ON CONFLICT (member_id) DO NOTHING;

INSERT INTO ai_db.faqs (category, question, answer, sort_order) VALUES
    ('배송', '배송은 얼마나 걸리나요?', '결제 완료 후 영업일 기준 2~3일 소요됩니다.', 1),
    ('주문', '주문 취소는 어떻게 하나요?', '배송 준비중 상태까지는 마이페이지에서 직접 취소할 수 있습니다.', 2);

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT schemaname, tablename,
               CASE schemaname
                   WHEN 'member_db'  THEN 'member_svc'
                   WHEN 'catalog_db' THEN 'catalog_svc'
                   WHEN 'order_db'   THEN 'order_svc'
                   WHEN 'ai_db'      THEN 'ai_svc'
               END AS owner
        FROM pg_tables
        WHERE schemaname IN ('member_db', 'catalog_db', 'order_db', 'ai_db')
    LOOP
        EXECUTE format('ALTER TABLE %I.%I OWNER TO %I', r.schemaname, r.tablename, r.owner);
    END LOOP;

    FOR r IN
        SELECT sequence_schema AS schemaname, sequence_name,
               CASE sequence_schema
                   WHEN 'member_db'  THEN 'member_svc'
                   WHEN 'catalog_db' THEN 'catalog_svc'
                   WHEN 'order_db'   THEN 'order_svc'
                   WHEN 'ai_db'      THEN 'ai_svc'
               END AS owner
        FROM information_schema.sequences
        WHERE sequence_schema IN ('member_db', 'catalog_db', 'order_db', 'ai_db')
    LOOP
        EXECUTE format('ALTER SEQUENCE %I.%I OWNER TO %I', r.schemaname, r.sequence_name, r.owner);
    END LOOP;
END $$;
