-- =============================================================================
-- 로컬 데모 데이터 (클러스터 A)
--
-- 여기 있는 CREATE TABLE 은 db/cluster-a/01~03 의 "목표 스키마"가 아니라
-- **현재 JPA 엔티티 모양**이다. 전환 전 저장소에서도 같은 구조였다 —
-- 엔티티와 schema.sql 이 아직 정렬되지 않았고(예: members 는 엔티티가
-- cognito_sub 를 쓰는데 목표 스키마는 username/password 를 쓴다),
-- docker-compose 는 ddl-auto: update 로 뜨기 때문이다.
--
-- 그래서 01~03 파일은 마운트하지 않는다. 그것들은 Flyway 로 넘어갈 때의
-- 목표 스키마 참조본이고, 실제 로컬 기동은 이 파일 + ddl-auto 가 담당한다.
-- (전환 전에도 schema.sql 을 넣지 않고 1_demo_data.sql 만 넣었던 것과 같다)
--
-- 각 테이블이 어느 스키마에 들어가는지가 MSA 전환의 결과물이다.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- member_db
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS member_db.members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cognito_sub  VARCHAR(255) NOT NULL UNIQUE,
    email        VARCHAR(255) NOT NULL UNIQUE,
    name         VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    gender       VARCHAR(10),
    birth_date   DATE,
    role         VARCHAR(20) NOT NULL DEFAULT 'USER',
    grade        VARCHAR(20) NOT NULL DEFAULT 'BRONZE',
    point        INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO member_db.members (cognito_sub, email, name, role, grade)
VALUES ('00000000-0000-0000-0000-000000000001', 'test@lion.com', '테스트유저', 'USER', 'BRONZE')
ON CONFLICT (cognito_sub) DO NOTHING;

-- ---------------------------------------------------------------------------
-- catalog_db
-- books 에 stock_quantity 가 없는 것이 Phase 0-1 의 결과다.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS catalog_db.categories (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    parent_id     BIGINT,
    sort_order    INT NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO catalog_db.categories (category_name, sort_order)
VALUES ('IT/컴퓨터', 1)
ON CONFLICT (category_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS catalog_db.books (
    book_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(200) NOT NULL,
    author            VARCHAR(100) NOT NULL,
    publisher         VARCHAR(100) NOT NULL,
    isbn              CHAR(13) NOT NULL UNIQUE,
    category          VARCHAR(100) NOT NULL,
    price             BIGINT NOT NULL,
    cover_image_url   VARCHAR(500),
    description       TEXT,
    detailed_synopsis TEXT,
    sale_status       VARCHAR(20) NOT NULL DEFAULT 'ON_SALE',
    published_date    DATE,
    sales_count       INT NOT NULL DEFAULT 0,
    rating_avg        DECIMAL(3, 2) NOT NULL DEFAULT 0.00,
    review_count      INT NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO catalog_db.books (
    title, author, publisher, isbn, category, price,
    cover_image_url, description, detailed_synopsis, sale_status, published_date, sales_count
) VALUES (
    '클라우드 엔지니어링 교재',
    '북이팅라이언',
    '라이언출판사',
    '9791100000001',
    'IT/컴퓨터',
    25000,
    'https://example.com/covers/cloud-engineering.jpg',
    '클라우드 엔지니어링의 기초부터 실전까지 다루는 교재입니다.',
    '1장 클라우드 개론, 2장 컨테이너와 오케스트레이션, 3장 CI/CD 파이프라인 구축, 4장 관측성과 운영을 다루며, 마지막 장에서는 실제 장애 대응 사례를 상세히 재구성하여 소개한다.',
    'ON_SALE',
    '2026-01-15',
    42
) ON CONFLICT (isbn) DO NOTHING;

CREATE TABLE IF NOT EXISTS catalog_db.reviews (
    review_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id       BIGINT NOT NULL,
    member_id     BIGINT NOT NULL,
    order_item_id BIGINT,
    nickname      VARCHAR(50),
    rating        INT NOT NULL,
    content       TEXT NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalog_db.wishlists (
    wishlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL,
    book_id     BIGINT NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wishlists_member_book UNIQUE (member_id, book_id)
);

CREATE TABLE IF NOT EXISTS catalog_db.recent_books (
    recent_book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT NOT NULL,
    book_id        BIGINT NOT NULL,
    viewed_at      TIMESTAMP NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_recent_books_member_book UNIQUE (member_id, book_id)
);

-- 리뷰를 쓰려면 이 권한이 먼저 있어야 한다. 운영에서는 order-service 가
-- 구매 확정 시 Redis Streams 로 발행하지만, 로컬 데모용으로 1건 심어둔다.
CREATE TABLE IF NOT EXISTS catalog_db.review_permissions (
    member_id     BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    book_id       BIGINT NOT NULL,
    nickname      VARCHAR(50),
    granted_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at       TIMESTAMP,
    PRIMARY KEY (member_id, order_item_id)
);

INSERT INTO catalog_db.review_permissions (member_id, order_item_id, book_id, nickname)
VALUES (1, 1, 1, '테스트유저')
ON CONFLICT (member_id, order_item_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- order_db
-- 재고가 여기 있다. catalog 는 이 테이블을 조회할 권한이 없고,
-- /internal/inventory API 를 통해서만 값을 얻는다.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_db.inventory (
    book_id    BIGINT PRIMARY KEY,
    stock      INT NOT NULL DEFAULT 0,
    version    BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO order_db.inventory (book_id, stock) VALUES (1, 100)
ON CONFLICT (book_id) DO NOTHING;

-- CREATE TABLE IF NOT EXISTS order_db.orders (
--     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     member_id  BIGINT NOT NULL,
--     book_id    BIGINT NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- orders/deliveries 는 여기서 만들지 않는다 — Order/Delivery 엔티티가 이미 있고
-- ddl-auto: update 가 order-service 기동 시 만든다(주문/결제 구현 이전에는 이 자리에
-- member_id+book_id 두 컬럼짜리 임시 테이블과 데모 행을 수동으로 만들었는데, 그게
-- Order 엔티티의 실제 컬럼(recipient_name/address/order_status 등 NOT NULL)과
-- 어긋나면서 ddl-auto 의 ALTER TABLE ADD COLUMN NOT NULL 이 매번 실패했다 —
-- 기존 행이 새 NOT NULL 컬럼 값을 가질 수 없어서다. cart_items/coupons/payments 등
-- 다른 order_db 테이블도 전부 같은 이유로 여기서 수동 생성하지 않는다).

-- CREATE TABLE IF NOT EXISTS order_db.deliveries (
--     id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     order_id        BIGINT NOT NULL UNIQUE,
--     courier_company VARCHAR(100),
--     tracking_number VARCHAR(100),
--     delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
--     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- INSERT INTO order_db.orders (member_id, book_id) VALUES (1, 1);
-- INSERT INTO order_db.deliveries (order_id, courier_company, tracking_number, delivery_status)
-- VALUES (1, 'CJ대한통운', '123456789', 'IN_TRANSIT')
-- ON CONFLICT (order_id) DO NOTHING;


-- ---------------------------------------------------------------------------
-- 소유권 이전 — GRANT 만으로는 부족하다.
--
-- 데모 테이블을 superuser 가 만들었기 때문에, ddl-auto: update 로 뜬 서비스가
-- 인덱스나 제약을 덧붙이려 하면 "must be owner of table ..." 로 실패한다.
-- (SELECT/INSERT 권한과 DDL 변경 권한은 별개다)
--
-- 운영에서는 Flyway 가 서비스 계정으로 마이그레이션하므로 이 문제가 없다.
-- 로컬에서만 필요한 보정이다.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT schemaname, tablename,
               CASE schemaname
                   WHEN 'member_db'  THEN 'member_svc'
                   WHEN 'catalog_db' THEN 'catalog_svc'
                   WHEN 'order_db'   THEN 'order_svc'
               END AS owner
        FROM pg_tables
        WHERE schemaname IN ('member_db', 'catalog_db', 'order_db')
    LOOP
        EXECUTE format('ALTER TABLE %I.%I OWNER TO %I', r.schemaname, r.tablename, r.owner);
    END LOOP;

    FOR r IN
        SELECT sequence_schema AS schemaname, sequence_name,
               CASE sequence_schema
                   WHEN 'member_db'  THEN 'member_svc'
                   WHEN 'catalog_db' THEN 'catalog_svc'
                   WHEN 'order_db'   THEN 'order_svc'
               END AS owner
        FROM information_schema.sequences
        WHERE sequence_schema IN ('member_db', 'catalog_db', 'order_db')
    LOOP
        EXECUTE format('ALTER SEQUENCE %I.%I OWNER TO %I', r.schemaname, r.sequence_name, r.owner);
    END LOOP;
END $$;
