apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ${K8S_NAMESPACE}
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
