dependencies {
    implementation project(':modules:common')
    implementation project(':modules:member')
    implementation project(':modules:book')
    implementation project(':modules:order')

    testImplementation 'com.h2database:h2'
    testImplementation 'org.springframework.security:spring-security-test'
}
